### ISSUE TITLE
How do we pass extra-vars into the binaries created ? 

### ISSUE THREAD

**Issue by samvarankashyap** [kriansa/ansible-bundler#1]
I created a playbook 
```
---
- hosts: localhost
  tasks:
    - name: test
      debug:
        msg: "{{ test_var | default('hello') }}"
```
I created the binary using bundle-playbook 
I was wondering how to pass extra-vars into the binary ??

**Comment by kriansa** [comment]
Oh, interesting, I haven't thought about that.

I'll draft something tonight and update it quickly to add support for variables.

**Comment by samvarankashyap** [comment]
@kriansa Thank you for the prompt reply Kriansa.
bundle-playbook is an interesting solution. 
I am considering to use it for packaging. 
https://github.com/CentOS-PaaS-SIG/linchpin 
If you are interested we can collaborate towards it. 
Thank you.

**Comment by kriansa** [comment]
Added support for playbook variables with new switch `--vars-file` on 2d55d42272b548ea1dae5e9802f195938270ba45
