### ISSUE TITLE
"Unexpected Exception" while using digits for name tasks in role

### ISSUE THREAD

**Issue by ingvarrwvw** [kriansa/ansible-bundler#12]
Hi.
How to repeat:
1. Create role with ansible-galaxy
2. Create any task
3. Include task in tasks/main.yml like this:
 - name: 1
   include_tasks: tasks/any_task.yml

 Create bundle and run it on target host:

PLAY [localhost] *****************************************************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: argument of type 'int' is not iterable

**Comment by kriansa** [comment]
This has nothing to do specifically to `ansible-bundler`, but to `ansible` itself.

In yaml, you can force a number to be a string by wrapping it in quotes, have you tried it?

```yaml
- name: "1"
```

**Comment by ingvarrwvw** [comment]
This is the problem of the bundler, because the ansible works out this playbook without errors

**Comment by kriansa** [comment]
If that's the case I'll reopen it so I can test this later. Have you tried the workaround I mentioned?

**Comment by ingvarrwvw** [comment]
When using string, it solve problem

**Comment by kriansa** [comment]
I'm closing this again since it's not an ansible-bundler issue.
