### ISSUE TITLE
RFE: Passing extra-vars at runtime to bundled binaries

### ISSUE THREAD

**Issue by samvarankashyap** [kriansa/ansible-bundler#2]
Though we have an option to pass variables as var-files argument
It kind of means that we are hardcoding variables which is as good as declaring variables inside the playbook. 

I would like to see a way where the extra-vars are passed to binary-file generated. 
for example :
if the following is the playbook 
```
---
- hosts: localhost
  tasks:
    - name: test
      debug:
        msg: "{{ test_var | default('hello') }}"
```
and we create a binary by 
```
bundle-playbook  test_playbook.yaml
```
creates: 
test_playbook.run 

I would like to pass extravars are runtime parameter as follows:
./test_playbook.run -e "testkey=testvalue"

**Comment by kriansa** [comment]
Awesome. I like this idea. It makes the output more flexible to slightly different deployment setups. 👍 

One small concern: as of now, the binary has a runtime flag `--debug` so we can see what's happening underneath.
Now we're adding a variable parameter. Sooner or later we'll end up having to establish a common interface for the output binary so it can be well documented for the end-user. WDYT?

**Comment by kriansa** [comment]
@samvarankashyap 

I've added support for runtime variables [described as a tiny binary interface](https://github.com/kriansa/ansible-bundler#binary-interface). Thanks for your input here! :+1:
