### ISSUE TITLE
env: ‘ansible-playbook’: No such file or directory

### ISSUE THREAD

**Issue by elleryq** [kriansa/ansible-bundler#4]
OS: Ubuntu 18.04

Steps:

0. Clean Ubuntu 18.04 and bundle my playbook to "playbook.run"
1. install python and python-pip: sudo apt-get install python python-pip
2. Run playbook.run: ./playbook.run

Output:
```
Installing ansible...
Collecting ansible
.... # ignore installing messages...
env: ‘ansible-playbook’: No such file or directory
```

Try to find out why:

0. Extract tarball attached in playbook.run to /tmp/foo
1. Change directory to /tmp/foo, then run "./run-playbook.sh"
2. The modules are installed successfully in "python-deps", but "python-deps/usr/bin" is not existed.  "ansible-playbook" is installed in "python-deps/home/$USER/.local/bin", not "python-deps/usr/bin", that's why "No such file or directory" appeared.
3. If I use sudo to run: "sudo -H ./run-playbook.sh", "ansible-playbook" is installed in "python-deps/usr/local/bin"

**Comment by kriansa** [comment]
Thanks for the detailed info. I will look at it tonight.

**Comment by kriansa** [comment]
@elleryq 

I've fixed this issue on release v1.2.0. Could you test it?

Also, I hope you don't need it, but to help you in case you need to debug, you can run the playbook binary with `--debug --keep-temp` and then run the `run-playbook.sh` manually.

**Comment by elleryq** [comment]
> @elleryq
> 
> I've fixed this issue on release v1.2.0. Could you test it?
> 
> Also, I hope you don't need it, but to help you in case you need to debug, you can run the playbook binary with `--debug --keep-temp` and then run the `run-playbook.sh` manually.

I had tested, it works!
Thanks.

**Comment by elleryq** [comment]
> @elleryq
> 
> I've fixed this issue on release v1.2.0. Could you test it?
> 
> Also, I hope you don't need it, but to help you in case you need to debug, you can run the playbook binary with `--debug --keep-temp` and then run the `run-playbook.sh` manually.

I had tested v1.6.0.
My environment is Ubuntu 18.04.

1. If I just run "./playbook.run", it works.
2. If I use "sudo -H ./playbook.run", it doesn't work.  The error message is "ansible-playbook: command not found"

I check PATH, it shows:

> PATH=/tmp/ansible-bundle.bky8G/python-deps/usr/bin:/tmp/ansible-bundle.bky8G/python-deps/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

But 'ansible-playbook' did installed in python-deps/usr/local/bin

> ls python-deps/usr/local/bin/
> ansible         ansible-connection  ansible-doc     ansible-inventory  ansible-pull
> ansible-config  ansible-console     ansible-galaxy  ansible-playbook   ansible-vault

**Comment by kriansa** [comment]
Sorry I missed this.

I'm working on a fix for that. Should be out this week.

**Comment by kriansa** [comment]
@elleryq can you test the version 1.7.0? I tested on a Ubuntu machine and it's working fine.

**Comment by elleryq** [comment]
> @elleryq can you test the version 1.7.0? I tested on a Ubuntu machine and it's working fine.

I had tested 1.7.0, it works now!
Thanks :)
