### ISSUE TITLE
Parameters in the binary file '-e <EXTRA_VARS>, --extra-vars=<EXTRA_VARS>' do not work

### ISSUE THREAD

**Issue by majorgearhead** [kriansa/ansible-bundler#8]
Played with this a bit and noticed that you list a way to override vars in the created binary file, however it does not work because you do not account for it in your case statement and in other places.

**Comment by kriansa** [comment]
Logically it makes sense. There's a catch-all in the case statement for the entry point script. 

:thinking: now I'm curious how it got implemented in the first place, I'm pretty sure I tested it somehow (see: #2)

I'll take a look at it. Thanks for the report.

**Comment by kriansa** [comment]
That has been fixed on v1.9.1. Would you try it out?

**Comment by kriansa** [comment]
I think 1.9 broke it in the first place (https://github.com/kriansa/ansible-bundler/compare/v1.8.0...v1.9.0)

**Comment by majorgearhead** [comment]
This works perfectly with version 1.9.1.  I have a rather complex playbook involving lots of role tasks that also needs a bunch of vars passed to it and it worked flawlessly.  I really appreciate your work and fast turnaround time on this.
